version: 1
pipeline:
  image: backtickse/task-examples

  cluster:
    default: docker
    docker:
      network: tasks
      hello: world
    kubernetes:
      namespace: default
      domain: cluster.backtick.se
    api:
      url: http://localhost:63258
      ws_url: http://localhost:1337
