kind: ServiceAccount
apiVersion: v1
metadata:
  name: cowait
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cowait-task
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "create", "list", "delete", "deletecollection"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "create", "list", "delete", "deletecollection"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["get", "create", "list", "delete", "deletecollection"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cowait-task
subjects:
- kind: ServiceAccount
  name: cowait
  namespace: cowait
roleRef:
  kind: ClusterRole
  name: cowait-task
  apiGroup: rbac.authorization.k8s.io
