# sets up permissions for the default service account in the default namespace
# pods: create/list/delete
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task-node
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "create", "list", "delete", "deletecollection"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "create", "list", "delete", "deletecollection"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["get", "create", "list", "delete", "deletecollection"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task-node
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: task-node
  apiGroup: rbac.authorization.k8s.io
