version: 1
pipeline:
  image: backtickse/sparky-test
  base: backtickse/task-spark

  cluster:
    default: docker
    docker:
      network: tasks
    kubernetes:
      namespace: default
      domain: cluster.backtick.se
  
  environment:
    AWS_ACCESS_KEY_ID: AKIASMZJSEC3JBSJKUMZ
    AWS_SECRET_ACCESS_KEY: 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