version: '2'
services:
  dask-notebook:
    build: './dask-notebook'
    image: 'backtickse/dask-notebook'
  dask:
    build: './dask'
    image: 'backtickse/task-dask'
  spark:
    build: './spark'
    image: 'backtickse/task-spark'