name: Build Images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build & publish task image
      run: bash ./build.sh --push --with-dashboard --with-notebook

  publish_pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip3 install --upgrade setuptools twine wheel cryptography==3.3.2

    - name: Build & publish python package
      run: bash ./publish.sh
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
